import type { BridgeError } from '@shared/types'

/** IPC channel names shared by main and preload. One place, so a typo cannot split them. */
export const CH = {
  fsTree: 'fs:tree',
  fsRead: 'fs:read',
  fsWrite: 'fs:write',
  fsCreateDir: 'fs:create-dir',
  fsCreateFile: 'fs:create-file',
  fsIndex: 'fs:index',
  fsColdDiff: 'fs:cold-diff',
  fsReadAsset: 'fs:read-asset',
  fsRename: 'fs:rename',
  fsDelete: 'fs:delete',
  fileRepairRename: 'file:repair-rename',
  fileRenamed: 'file:renamed',
  fileDeleted: 'file:deleted',
  shellReveal: 'shell:reveal',
  dialogPickFolder: 'dialog:pick-folder',
  watchSubscribe: 'watch:subscribe',
  watchUnsubscribe: 'watch:unsubscribe',
  watchEvent: 'watch:event',
  stateGet: 'state:get',
  stateSetSettings: 'state:set-settings',
  stateSetSidebarCollapsed: 'state:set-sidebar-collapsed',
  statePushRecent: 'state:push-recent',
  stateRemoveRecent: 'state:remove-recent',
  stateSetFolder: 'state:set-folder',
  stateSetFolds: 'state:set-folds',
  stateSetBaseGroups: 'state:set-base-groups',
  stateChanged: 'state:changed',
  windowIdentity: 'window:identity',
  windowSetIdentity: 'window:set-identity',
  windowOpen: 'window:open',
  windowDuplicate: 'window:duplicate',
  windowCloseSelf: 'window:close-self',
  menuOpenFolder: 'menu:open-folder',
  menuOpenRoot: 'menu:open-root',
  menuCloseTab: 'menu:close-tab',
  menuNextTab: 'menu:next-tab',
  menuPrevTab: 'menu:prev-tab',
  linkOpenFile: 'link:open-file',
  linkNotice: 'link:notice',
  vaultConfigRead: 'vaultConfig:read',
  vaultConfigWrite: 'vaultConfig:write',
  vaultConfigChanged: 'vaultConfig:changed',
  registryGet: 'registry:get',
  registrySetType: 'registry:set-type',
  registryRemoveType: 'registry:remove-type',
  registrySetProperty: 'registry:set-property',
  registryRemoveProperty: 'registry:remove-property',
  registryChanged: 'registry:changed',
  appFlush: 'app:flush',
  appFlushed: 'app:flushed',
} as const

/**
 * Every `ipcMain.handle` answers with an envelope: Electron serialises a thrown Error down to
 * its message, so a structured `BridgeError` must travel as data. The preload unwraps it.
 */
export type Envelope<T> = { ok: true; value: T } | { ok: false; error: BridgeError }
